# Site settings
title: Predictive Edge Documentation
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
